# Generated by Django 4.0.4 on 2023-01-09 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_producto_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
    ]
