# Generated by Django 4.0.4 on 2023-01-09 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_producto_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='price',
        ),
    ]
