# Generated by Django 4.0.4 on 2023-01-09 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_remove_producto_precio_producto_precios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precios',
        ),
    ]
