# Generated by Django 4.0.4 on 2023-01-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_remove_producto_precios'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='dinero',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
