# Generated by Django 4.0.4 on 2023-01-10 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_producto_dinero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaprod',
            options={'verbose_name': 'CategoriaProd', 'verbose_name_plural': 'CategoriasProd'},
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='dinero',
            new_name='precio',
        ),
    ]
