# Generated by Django 4.0.4 on 2023-01-10 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_categoriaprod_options_remove_producto_precio'),
        ('tienda', '0012_remove_producto_precio'),
    ]

    operations = [
    ]
